# Generated by Django 2.0 on 2018-01-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessingGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=50)),
                ('game_description', models.TextField()),
            ],
            options={
                'ordering': ['game_title'],
            },
        ),
    ]
