# Generated by Django 2.0 on 2018-01-10 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=50)),
                ('item_value', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GuessingGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=50)),
                ('game_description', models.TextField()),
            ],
            options={
                'ordering': ['game_title'],
            },
        ),
        migrations.AddField(
            model_name='gameitem',
            name='guessing_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guessing_games.GuessingGame'),
        ),
    ]
