# Generated by Django 2.0 on 2018-01-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=50)),
                ('item_value', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
