# Generated by Django 2.0 on 2018-01-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guessinggame',
            options={'ordering': ['game_title'], 'verbose_name_plural': 'Vendespil'},
        ),
    ]
