# Generated by Django 2.0 on 2018-01-10 22:00

from django.db import migrations, models
import django.db.models.deletion
import guessing_games.models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing_games', '0002_gameitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='guessing_game',
            field=models.ForeignKey(default=guessing_games.models.GuessingGame, on_delete=django.db.models.deletion.CASCADE, to='guessing_games.GuessingGame'),
        ),
    ]
